version: "3.8"

services:
  ml_api_db:
    image: postgres:alpine
    ports:
      - 5436:5432
    hostname: ml_api_db
    env_file: .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  ml_api_be:
    env_file: .env
    build: .
    ports:
      - 5000:5000
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - ml_api_db
    volumes:
      - .:/app
